top_srcdir   = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
top_builddir = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
srcdir       = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/os
builddir     = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/os
VPATH        = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
