top_srcdir   = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
top_builddir = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
srcdir       = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/server/mpm
builddir     = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/server/mpm
VPATH        = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
