top_srcdir   = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
top_builddir = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
srcdir       = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/os/unix
builddir     = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/os/unix
VPATH        = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
