top_srcdir   = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
top_builddir = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
srcdir       = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/modules/metadata
builddir     = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/modules/metadata
VPATH        = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/modules/metadata

include $(top_srcdir)/build/special.mk

