top_srcdir   = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
top_builddir = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
srcdir       = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/modules/core
builddir     = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/modules/core
VPATH        = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/modules/core

include $(top_srcdir)/build/special.mk

