top_srcdir   = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
top_builddir = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28
srcdir       = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/modules/proxy/balancers
builddir     = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/modules/proxy/balancers
VPATH        = /home/ablaauwgeers/os3/cia/a8/httpd-2.4.28/modules/proxy/balancers
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
